### ISSUE TITLE
Error in gulp after updating to version 0.0.8

### ISSUE THREAD

**Issue by matochondrion** [zhouwenbin/postcss-animation#5]
This might just be me, but as of version 0.0.8, when I run gulp I get an error.  This doesn't happen in version 0.0.7.
I'm using Node  v5.11.1

The line that appears to cause the problem is:
`          animation: slideInUp 1s;`

from the following css rule:

```
        .product-name {
          display: block;
          animation: slideInUp 1s;
        }
```
The error message is:
> { [TypeError: Cannot read property 'type' of undefined]
>   name: 'TypeError',
>   message: 'Cannot read property \'type\' of undefined',
>   stack: 'TypeError: Cannot read property \'type\' of undefined\n    at Root.normalize (/Users/rms/Dropbox (Personal)/Freelance/TCS9999/site/node_modules/postcss/lib/container.js:413:22)\n    at Root.normalize (/Users/rms/Dropbox (Personal)/Freelance/TCS9999/site/node_modules/postcss/lib/root.js:46:52)\n    at Root.insertAfter (/Users/rms/Dropbox (Personal)/Freelance/TCS9999/site/node_modules/postcss/lib/container.js:302:26)\n    at /Users/rms/Dropbox (Personal)/Freelance/TCS9999/site/node_modules/postcss-animation/index.js:31:44\n    at Array.forEach (native)\n    at /Users/rms/Dropbox (Personal)/Freelance/TCS9999/site/node_modules/postcss-animation/index.js:26:14\n    at /Users/rms/Dropbox (Personal)/Freelance/TCS9999/site/node_modules/postcss/lib/container.js:106:28\n    at /Users/rms/Dropbox (Personal)/Freelance/TCS9999/site/node_modules/postcss/lib/container.js:81:26\n    at Rule.each (/Users/rms/Dropbox (Personal)/Freelance/TCS9999/site/node_modules/postcss/lib/container.js:68:22)\n    at Rule.walk (/Users/rms/Dropbox (Personal)/Freelance/TCS9999/site/node_modules/postcss/lib/container.js:80:21)',
>   fileName: '/Users/rms/Dropbox (Personal)/Freelance/TCS9999/site/builds/components/postcss-single-page-workflow/css/style.css',
>   showStack: true,
>   showProperties: true,
>   plugin: 'gulp-postcss' }

**Comment by zhouwenbin** [comment]
@matochondrion try to use node v4.2.0

**Comment by matochondrion** [comment]
@zhouwenbin Thanks for the suggestion.  I tried v4.2.0 with postcss-animation 0.0.8 but got the same error.  Tried with 0.0.7 and it worked.  Maybe it's just something on my system?

**Comment by zhouwenbin** [comment]
@let me see,v0.0.8 merge some code.

**Comment by zhouwenbin** [comment]
@matochondrion https://github.com/zhouwenbin/postcss-animation-example try this!

**Comment by matochondrion** [comment]
@zhouwenbin your test worked for me.  I tested further...

changed:
`animation-name: bounce;`
to
`animation: bounce;`
Which worked. But when I added 1s:
`animation: bounce 1s;`
I got errors again.

**Comment by zhouwenbin** [comment]
@matochondrion i solved this problem.update to v0.0.9

**Comment by matochondrion** [comment]
Works, thank you!

**Comment by zhouwenbin** [comment]
@matochondrion you are welcome
