### ISSUE TITLE
Bug: Works only once

### ISSUE THREAD

**Issue by dmitrykiselyov** [zhouwenbin/postcss-animation#8]
Hi @zhouwenbin,
Thank you for the plugin!
 
When `watch` it works only once.
Here's the video with this bug:
https://jumpshare.com/v/SmQK7SGwRNUGZamOYcal+/Screencast+2017-03-06+at+3.31.26+PM.mp4

**package.json**
```json 
{
  "dependencies": {
    "postcss-animation": "0.0.11",
    "postcss-cli": "^3.0.0-beta"
  },
  "scripts": {
    "watch": "postcss styles.css -o styles-postcss.css -u postcss-animation -w --no-map"
  }
}
```
**styles.css**
```css

.foo {
  animation-name: bounce;
}
```

**Comment by zhouwenbin** [comment]
@dmitrykiselyov Thank you.Update 0.0.12 to fix
